package br.com.cabalistica.sergiobismark.numerologiacabalistica;

import android.content.Intent;
import android.support.design.widget.FloatingActionButton;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.MultiAutoCompleteTextView;

public class Destino extends AppCompatActivity {
    private MultiAutoCompleteTextView edtdestino;
    private FloatingActionButton x1;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        final Intent intent = new Intent(Destino.this, LicoesCarmicas.class);

        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_destino);

        edtdestino = (MultiAutoCompleteTextView) findViewById(R.id.edtdestino);

        FloatingActionButton x1 = (FloatingActionButton) findViewById(R.id.x1);
        x1.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                startActivity(intent);

            }
        });

        Bundle bundle = getIntent().getExtras();

        String nomecompleto = bundle.getString("NOME");
        int valor1 = bundle.getInt("VALORES1");
        int valor2 = bundle.getInt("VALORES2");
        int valor3 = bundle.getInt("VALORES3");
        String valor4 = bundle.getString("VALORES4");
        String valor5 = bundle.getString("VALORES5");
        int valor6 = bundle.getInt("VALORES6");
        int valor7 = bundle.getInt("VALORES7");
        String valor8 = bundle.getString("VALORES8");
        int valor9 = bundle.getInt("VALORES9");
        String valor10 = bundle.getString("VALORES10");
        int valor11 = bundle.getInt("VALORES11");
        int valor12 = bundle.getInt("VALORES12");
        int valor13 = bundle.getInt("VALORES13");
        int valor14 = bundle.getInt("VALORES14");
        int valor15 = bundle.getInt("VALORES15");
        String valor16 = bundle.getString("VALORES16");
        String valor17 = bundle.getString("VALORES17");
        int valor18 = bundle.getInt("VALORES18");
        int valor19 = bundle.getInt("VALORES19");
        int valor20 = bundle.getInt("VALORES20");
        int valor21 = bundle.getInt("VALORES21");
        int valor22 = bundle.getInt("VALORES22");
        String valor23 = bundle.getString("VALORES23");
        String valor24 = bundle.getString("VALORES24");
        int valor25 = bundle.getInt("VALORES25");
        int valor26 = bundle.getInt("VALORES26");
        int valor27 = bundle.getInt("VALORES27");
        String valor28 = bundle.getString("VALORES28");


        String ler = "Este é um dos números mais importantes do Mapa Numerológico. Ele descreve as influências na personalidade, oportunidades e os obstáculos que uma pessoa irá encontrar ao longo da sua vida. Indica, ainda, as alternativas disponíveis e o provável resultado de cada uma delas.\n\n";
        String numero = "";
        if (valor21 == 1) {
            numero = "                   VIBRAÇÃO “1” \n PONTOS POSITIVOS: Pioneirismo, iniciativa, grande capacidade de liderança, inventividade, capacidade de comando e espírito executivo. Devido a estas características, o consulente com esta vibração, normalmente tem êxito e prosperidade em quase todas as atividades. Normalmente é um ser talentoso e espirituoso, em geral uma pessoa ativa e produtiva, dotada de uma inteligência aguçada e perspicaz Se for estimulado por um projeto que considere valer a pena, tem o talento, a vitalidade e a capacidade para realizações extraordinárias. O 1 necessita de brilho, de reconhecimento e sucesso. Para conseguir esse estágio, se dedicam exaustivamente ao trabalho e normalmente são os melhores na sua área de atuação. Quem com ele convive, fica muito intrigado, pois demonstra sempre um semblante feliz, alegre, descontraído e, acima de tudo, de muita confiança em suas realizações, mesmo que tudo isso não seja verdade.\n PONTOS NEGATIVOS: Tendência à arrogância, egoísmo, prepotência, excesso de ânimo e dominação, por vezes achando que o sucesso do grupo dependeu exclusivamente dele. Esse tipo de postura pode tornar difícil o convívio com os amigos e colegas de trabalho, além de dificultar o relacionamento a dois, pois não é nada fácil conviver com esse tipo de pessoa. Um dos obstáculos à sua realização pessoal é a tendência a sobrecarregar o seu sistema nervoso com uma atitude crítica e preocupada. Como isso pode isolá-lo dos outros, precisa ter fé em si mesmo e nas suas habilidade e aproveitar ao máximo suas idéias originais e inventivas.\n ORIENTAÇÃO: Como não gosta de receber ordens, deve sempre procurar trabalhar por conta própria ou em cargo de chefia. Sendo individualista, íntegro e honesto em seus propósitos, deve aprender a ser pioneiro, a trabalhar em grupo e a ser comandante, não ditador; a ouvir conselhos, analisar situações e, após meditar sobre o assunto, tomar decisões. Ou seja, não agir precipitadamente.";
        }
        else if (valor21 == 2){
            numero = "                   VIBRAÇÃO “2” \n PONTOS POSITIVOS: É o número das associações com outras pessoas; aquele capaz de unir, juntar idéias e fatos e contribuir para a realização de qualquer projeto. Possui grande capacidade para assimilar idéias alheias, valorizá-las e condensá-las, de forma a criar um clima de satisfação em todos os envolvidos. Tem habilidades diplomáticas naturais e sabe deixar os outros à vontade. Normalmente as pessoas se sentem atraídas por sua gentileza e maneiras refinadas e normalmente se ajusta bem a trabalhos em conjunto. É amigo leal, excelente pai ou mãe e faz grande questão de proteger os familiares, amigos ou simplesmente colegas de trabalho. Quando consegue ver as pessoas e situações a partir de uma perspectiva superior, pode dar muito de si, ao mesmo tempo em que se mantém distante, confiando que a vida irá naturalmente resolver as coisas no tempo devido.\n  PONTOS NEGATIVOS: Tem tendência ao acomodamento e a esperar que os outros tomem a iniciativa, procurando manter-se na retaguarda, aparecendo pouco. Como não é pioneiro ou individualista quanto aos seus projetos de vida, é muito comum perder excelentes oportunidades por causa disso, não notando que o tempo vai passando e os projetos e ideais vão ficando cada vez mais distantes. No lado psicológico, quando está com disposição negativa (o que não é raro), corre o risco de se sacrificar ou de se deixar levar pela autopiedade ou comodismo.\n ORIENTAÇÃO: Precisa cultivar a paciência, cooperação, tato, lealdade, aplicação e capacidade de seguir a orientação dos outros. Sendo o seu principal atributo a união, deve aprender a unir todos aqueles que desejam essa parceria. Porém, não deve interferir (o que normalmente faz) naqueles que não desejam estar unidos. Trabalhe sempre em parceria; se não existir, procure. Não fique parado esperando que as coisas caiam do céu ou que apareça alguém do nada para lhe ajudar a resolver seus problemas.";
        }
        else if (valor21 == 3){
            numero = "                   VIBRAÇÃO “3” \n PONTOS POSITIVOS: É o Destino da sociabilidade. O 3 é alegre, versátil e talentoso. É criativo, social e possui o dom artístico, seja falando, representando, escrevendo, pintando ou desenvolvendo qualquer outro tipo de arte. Ao longo da sua existência deve sempre procurar cultivar esses dotes, ou seja, a criatividade, os contatos sociais e a expressão de suas idéias e sentimentos. Tudo o que faz cresce e se multiplica. Tem, na comunicação, como um todo, o seu principal trunfo para ser próspero e feliz. A emoção e a criatividade são as razões do seu sucesso, pois tem extraordinária facilidade de expressão e também grande capacidade executiva. Dinâmico e versátil, tem uma personalidade charmosa e habilidade para promover suas idéias. Quanto mais se dedicar ao trabalho, melhores serão os resultados e recompensas. Pode ser bem sucedido como vendedor, professor, relações públicas, nas artes plásticas ou cênicas ou em contato com o público.\n PONTOS NEGATIVOS: Entedia-se facilmente, é vaidoso em demasia, impaciente, extravagante, exagerado, esbanjador, com certa irresponsabilidade para cumprir horários e desprezar pessoas com nível inferior ao seu. Quando essas características se manifestam, torna-se completamente insociável, disperso e com grande tendência a se entediar, a se isolar e ter crises nervosas.\n ORIENTAÇÃO: Como nasceu com o dom da palavra, da comunicação, deve usar esse dom intuitivo para alcançar sucesso em trabalhos mentais. Embora o dia 3 faça com que seja artístico e charmoso, dotado de um bom senso de humor, precisa desenvolver a auto-estima e evitar as tendências a se preocupar ou se sentir emocionalmente inseguro.  Deve, ainda, manter sob controle suas necessidades de movimentação e os excessos de atividades corriqueiras. Seja mais seleto nas amizades, ou seja, procure qualidade à quantidade.";
        }
        else if (valor21 == 4){
            numero = "                   VIBRAÇÃO “4” \n PONTOS POSITIVOS: É o Destino da conquista, por meio do trabalho duro e incansável. Necessita cultivar a paciência, a confiança e a disposição para servir. Sua vida, em geral, não é muito fácil, em termos de retorno e exigências. Terá de trabalhar muito, com muita dedicação para manter a vida financeira, afetiva e social. Porém, tudo o que consegue é sólido e eterno. Dedica-se de corpo e alma aos seus projetos e conquistas e quase sempre é bem sucedido profissionalmente.Tem poucos amigos, porém sinceros e não se interessa por quantidade, preferindo a qualidade em tudo e em todos. Sensível, cheio de idéias criativas e com senso de visão, tem potencial para expressar os seus conceitos originais e inspirados. Isso pode ajudá-lo a superar possíveis preocupações quanto à sua instabilidade financeira e a tomar as decisões corretas.Em si repousa a segurança e a estabilidade para manter tudo e todos que dele dependem.\n PONTOS NEGATIVOS: Como é muito estruturado, conservador e inflexível, viver em grupo é extremamente difícil e quase sempre rejeita o novo, pois essa incerteza lhe transmite insegurança e possibilidades de perdas. É perfeccionista ao extremo e cobra demais dos outros, sejam familiares, amigos ou subordinados, tornando-se por vezes chato e incompreendido. Se levar uma vida negativa, poderá se inclinar para assuntos fraudulentos, conspirações, orgulho demasiado ou a planos astutos e maléficos para enriquecer rapidamente às custas do sofrimento alheio.\n ORIENTAÇÃO: Deve viver ponderadamente, desenvolver o senso de responsabilidade moral, equilíbrio no poder e correta aplicação do saber em todos os seus projetos e realizações. Para viver sem muitos altos e baixos, precisa praticar a justiça, a ponderação e serviço a terceiros, sempre que a oportunidade se oferecer. Deve se relacionar positivamente com todos e respeitar o direito que eles tem de errarem. Deve, também, se relacionar com pessoas inteligentes e com as quais possa compartilhar os seus interesses.";
        }
        else if (valor21 == 5){
            numero = "                   VIBRAÇÃO “5” \n PONTOS POSITIVOS: É o viajante, sempre desejoso de mudanças e de novidades. Esta vibração pertence às pessoas versáteis, no sentido de mudar, alterar e transformar. Está sempre à procura do que é novo, moderno, diferente. Esta procura também se estende pelo âmbito do saber , aprender e conhecer, muito mais do que por capricho ou prazer. É alegre, comunicativo, inteligente e receptivo, sempre bem vindo em qualquer roda. Curioso, dotado de capacidade de discernimento, geralmente procura se fortalecer através do conhecimento. Com ele não existe “mau tempo”; está sempre de bem com a vida e, por isso, por vezes é confundido e até tachado de irresponsável, coisa que não é, em absoluto. Como é mentalmente ativo, gosta de um bom desafio intelectual. Contudo, a sua inclinação para se envolver em disputas implica que quando não consegue o que quer pode ficar irascível.\n  PONTOS NEGATIVOS: Normalmente compra mais coisas do que necessita e pode pagar, levando-o a ter alguns problemas financeiros ao longo da vida. No lado sentimental, busca relações novas e intrigantes, que são as que o atraem, e às vezes se envolve em situações afetivas de que dificilmente se desvencilha. É um ser extrovertido com ampla visão de tudo e de todos, mas inconstante em seus objetivos, levando-o a ter muitos começos e poucos fins.\n  ORIENTAÇÃO: Para evitar os aspectos negativos prejudiciais ao desenvolvimento pessoal, deve desenvolver o poder de análise e seleção, aproveitando as experiências para aperfeiçoar e elevar seu caráter e sentir uma nobre afinidade humana isenta de interesses particulares, sexuais ou materiais. Como vive quase que exclusivamente no presente, é aconselhável trabalhar com um propósito definido, com um objetivo altruísta e levá-lo até o fim, aconteça o que acontecer. Lembre-se que a desordem não faz parte do Universo; logo, quando encontrar desordem, mude; mude a desordem em  uma nova ordem. Será um bom psicólogo, historiador, professor, jurista, conferencista ou carreiras que tenham contato com o público. Como admira pessoas poderosas e independentes, precisa de um parceiro que o enfrente e que não se intimide com a sua personalidade vigorosa. Embora seja amigável e sociável, gosta de fazer as coisas sozinho e de enfrentar novos desafios. Como gosta de exercitar o seu poder cerebral, prefere a companhia de pessoas inteligentes.";
        }
        else if (valor21 == 6){
            numero = "                   VIBRAÇÃO “6” \n PONTOS POSITIVOS: O 6  é normalmente dócil, educado, não suporta brigas e desentendimentos e quer sempre manter tudo calmo e tranqüilo. É o número da harmonia, do lar e do amor. Compaixão, idealismo e natureza atenciosa são algumas das qualidades sugeridas por este dia admirável. É o número do perfeccionista ou do amigo universal e em muitos casos, humanitário, responsável e amoroso. Adora crianças, plantas e animais. A sua forte personalidade, combinada com sua capacidade amorosa e seu charme, pode ser muito atraente para os demais. É ambicioso mas também compreensivo e encorajador, com disposição de fazer qualquer coisa pelas pessoas que ama. Detesta aglomerações e festividades excessivas, gosta da harmonia e de viver em paz. Geralmente se dá bem em relacionamentos afetivos, pois é amável e muito gentil. \n PONTOS NEGATIVOS: É por demais sentimental, vulnerável e crédulo, sempre confiando nas aparências sem analisar os fatos friamente. Tem, normalmente, dois problemas: o acomodamento e a falta de interesse. Por ser profundo, necessita de tranqüilidade para, no mínimo, aparentar estar bem consigo mesmo. Quanto ao interesse, necessita ser constantemente incentivado, pois caso contrário tem tendência a deixar tudo a meio caminho. Na tentativa de manter tudo calmo e tranqüilo, por vezes acaba interferindo de maneira não condizente com o momento, pois nem sempre a docilidade é o melhor remédio para certas situações, e isso o perturba sobremaneira, levando-o a se retrair e a acomodar-se, até que outro fato ou circunstância o incentivem.\n  ORIENTAÇÃO: Como é o Destino da responsabilidade e da liderança, necessita aprender a se ajustar a condições pouco harmoniosas, a assumir o fardo dos outros, a defender suas próprias idéias e a servir com alegria. Apesar de seus ideais elevados, precisa ser determinado, ter paciência e perseverança para atingir as suas metas. Deve trabalhar com o público, pois conquista amizades e simpatias com grande facilidade, sendo respeitado e amado por todos.";
        }
        else if (valor21 == 7){
            numero = "                   VIBRAÇÃO “7” \n PONTOS POSITIVOS: Normalmente é uma pessoa que busca na vida o entendimento, o conhecimento mais profundo e qualitativo. No desenrolar de sua vida sempre procurará ser eficiente, intuitivo, perfeccionista, meticuloso, racional, reflexivo, concentrado, reservado, compreensivo e amoroso, apesar de não demonstrar qualquer desses sentimentos altruístas. Busca sempre o lado oculto das coisas e das pessoas. Nunca se satisfaz com as aparências, preferindo conhecer a essência.  Com uma necessidade constante de ter uma maior autoconsciência, gosta de reunir informações e se interessa por ler, escrever por assuntos espirituais. A tendência a ser enigmático ou reservado sugere que pode ocasionalmente se sentir mal interpretado.\n  PONTOS NEGATIVOS: Por vezes tem espírito dominador, crítico, exigente, perfeccionista, angustiado, impaciente, orgulhoso e aparentemente descrente. Embora seja pragmático por natureza, pode, às vezes, ter idéias pouco convencionais; tome cuidado, porém, para que isso não vire uma desculpa para ser do contra somente para se fazer de difícil. Deve, também, aprender a valorizar as pessoas como elas são, ou seja, respeitar o fato de os outros serem fruto daquilo que conseguiram absorver da vida e do convívio com os demais.\n  ORIENTAÇÃO: O 7 é o Destino da sabedoria e também o da solidão, por isso necessita desenvolver seus poderes mentais, estudar, meditar, buscar o significado último da vida. Enfim, tornar-se um especialista. Com sua inteligência arguta, sua habilidade de liderança e poder inerente a este dia, pode ter muitas oportunidades profissionais e ser bem sucedido em qualquer uma delas. Pode ser escritor, advogado, pesquisador, religioso, pesquisador ou trabalhar simplesmente para desenvolver espiritualmente o planeta. Contudo, evite usar o poder de forma destrutiva e se rebelar contra os outros, pois o “tiro pode sair pela culatra”, ou seja, você ser o prejudicado no final.";
        }
        else if (valor21 == 8){
            numero = "                   VIBRAÇÃO “8” \n PONTOS POSITIVOS: É aquele que tem capacidade para planejar, organizar e levar a efeito qualquer tipo de negócio. O seu Destino é o ganho financeiro e material. Individualista, inteligente e sensível, tem uma personalidade exigente. Embora seja ambicioso e vigoroso, e tenha coragem e lealdade aos seus ideais, é também muito gentil e generoso com os que ama. Geralmente não apresenta problemas financeiros, pois caso não seja herdeiro, é empreendedor. Objetividade é o seu lema. É justo, disciplinado, honesto, amigo, econômico, elegante e bom negociante. A sua necessidade de crescimento e habilidade para rever o todo sugere que gosta de pensar em grandes termos. Confiante e curioso, não gosta de interferências de outras pessoas e, com a inclinação à teimosia, pode tornar-se inquieto e impaciente.\n  PONTOS NEGATIVOS: Como está sempre sendo impulsionado para ganhar dinheiro e para conquistas materiais, por vezes se esquece da família, do lado sentimental, social e, principalmente, de si próprio. Apresenta, também, acentuada dificuldade em demonstrar afeto e carinho, aparentando frieza nos relacionamentos em geral. Na realidade, é um ser altamente emotivo, necessitando de ajuda e compreensão por parte das pessoas mais chegadas.\n ORIENTAÇÃO: Precisa cultivar a eficiência na arte de negociar  e compreender as leis que comandam a acumulação, o poder e o uso do dinheiro. Para aproveitar ao máximo a sua inteligência rápida, sua necessidade de expressão e o lado sociável da sua natureza, precisa superar a inclinação à incerteza ou à indecisão nos seus relacionamentos emocionais. Necessita aprender que as pessoas precisam de atenção. Por isso, fique atento: quanto maior for a ostentação, mais as pessoas concluirão que você não precisa delas. E, se em algum momento você realmente precisar, elas não estarão por perto.  Como tem grande capacidade executiva, pode ser advogado, executivo de grandes empresas, vendedor (por conta própria), professor, político, missões religiosas ou conselheiro.";
        }
        else if (valor21 == 9){
            numero = "                   VIBRAÇÃO “9” \n PONTOS POSITIVOS: É o Destino da universalidade. A pessoa com este Destino normalmente é espirituosa, charmosa, divertida e amorosa, mas o seu desejo de ser bem sucedido deriva de uma interessante mistura de materialismo e idealismo. Benevolência, ponderação e sensibilidade emocional estão associadas a este dia. Tolerante e gentil, é na maior parte das vezes generoso e liberal. Sua intuição e seu poder psíquico indicam uma receptividade universal que, se positivamente canalizada, pode inspirá-lo a buscar o caminho espiritual. Necessita que as pessoas ao seu redor estejam bem, pois caso contrário tudo fará para que isso aconteça. Sua necessidade de auxílio é voltada para o todo, para a humanidade e não para uma pessoa ou um caso especial. Preocupa-se com tudo que esteja em desacordo com suas inspirações, é muito emotivo e por demais sentimental.\n  PONTOS NEGATIVOS: Como vive para o mundo, por vezes acaba perdendo excelentes oportunidades, principalmente no âmbito profissional. Embora seja idealista e generoso, pode ser reservado e, em algumas ocasiões, ocultar sentimentos profundos que podem se transformar em ressentimentos.  Frustra-se com certa facilidade, é pouco prático, de certa maneira egoísta, tem dias amargos, complexo de inferioridade, medos, preocupação exagerada e tendência ao isolamento.\n  ORIENTAÇÃO: Necessita servir e se divertir. Precisa aprender a amar o próximo, a livrar-se dos preconceitos, ser generoso, tolerante e compreensivo com seus semelhantes. Este número sugere a necessidade de superar desafios e a tendência a ser excessivamente sensível e passível de instabilidade emocional. Pode-se beneficiar de viagens internacionais e da interação com pessoas de diversos círculos sociais, mas deve evitar os sonhos irrealistas ou a inclinação ao escapismo. Com sua grande capacidade para adquirir conhecimentos, pode ser bem sucedido no meio acadêmico ou nas áreas de advocacia, psicologia, medicina, literatura, ou ainda nas artes plásticas de um modo geral e, principalmente, no meio esotérico.";
        }
        else if (valor21 == 11){
            numero = "                   VIBRAÇÃO “11” \n PONTOS POSITIVOS: É o Destino da inspiração. É o número das pessoas altamente sensíveis e intuitivas. O 11 possui facilidade de ver, não somente a realidade atual, mas também os seus desdobramentos. Enxergam longe. Normalmente são impacientes e dotados de certo nervosismo Sensível e idealista, é normalmente uma pessoa enérgica, com enorme potencial mental quando está disposto a se disciplinar através da concentração nos seus objetivos. Versátil e imaginativo, precisa expressar o seu poder criativo e emocional. A compostura e a perseverança são freqüentemente a chave para o seu sucesso, e pode impressionar quando se especializa em uma área específica. O número-mestre 11 sugere que o idealismo, a inspiração e a inovação são altamente importante para ele. Uma combinação de humildade e confiança o desafia a trabalhar para alcançar a independência financeira e espiritual. É concentrado, objetivo, inspirador, muito espiritualizado, intuitivo, expansivo, prestativo, tem grande habilidade para curar, é humanitário e psíquico.\n  PONTOS NEGATIVOS: Tendência a vícios, falta de objetivos, complexo de superioridade, magoa-se com facilidade, hipersensível, excessivamente emotivo, de certa forma egoísta e, quando as coisas não correm como quer, pode-se tornar desonesto no afã de conseguir o que quer. Como é altamente sensível, capta com maior intensidade as imperfeições do mundo e das pessoas. Com isso, vai acumulando insatisfações e sofrimentos. Essas insatisfações e sofrimentos, devem servir para melhorar sempre os seus conceitos sobre tudo e todos.\n  ORIENTAÇÃO: Precisa investigar o misticismo, confiar na própria intuição, ter fé, conservar-se humilde diante da notoriedade e inspirar os outros através do seu exemplo. Como a Natureza lhe dotou de certos atributos que não deu aos demais, deve usá-los para melhorar o planeta, os seus semelhantes e a própria vida. Não exija demais dos outros ou que eles compreendam ou façam o mesmo que você. Embora precise de liberdade para agir de forma independente, evite se preocupar demais consigo mesmo e aprenda a trabalhar com as outras pessoas. Quando combina seu pensamento imaginativo com sua habilidade e praticidade, pode obter resultados extraordinários.";
        }
        else if (valor21 == 22){
            numero = "                   VIBRAÇÃO “22” \n PONTOS POSITIVOS: É o Destino do mestre construtor que se dedica altruisticamente à humanidade. É, também, o número da Sabedoria. As pessoas com esta vibração são normalmente precoces em todas as atividades, sejam elas de cunho material, social, mental ou espiritual. Conhecem da vida o superficial, o profundo e o invisível, e possuem uma capacidade nata para o ensino. O Destino mestre 22 é orgulhoso, prático e altamente intuitivo. Normalmente honesto e trabalhador, com capacidade natural para a liderança, possui uma personalidade carismática e uma compreensão profunda das pessoas e de suas motivações. Apesar de ser reservado, muitas vezes tem uma preocupação atenciosa e protetora com o bem-estar das pessoas, mas nunca perde de vista a sua posição realista e pragmática. Em geral culto e mundano, tem muitos amigos e admiradores. Os que são mais competitivos, podem alcançar o sucesso e a fortuna com a ajuda e o encorajamento dos amigos e familiares. Charmoso, talentoso, comunicativo e diplomata natural, pode seguir carreiras nas áreas de vendas, promoções, agências ou de relações públicas. Da mesma forma, pode se dedicar ao mundo das comunicações, área editorial, política, educação, medicina e, principalmente, à área holística, ajudando a humanidade. Além de todos estes dons, ainda possui facilidade de entender e desenvolver processos de alta magia, entendida como uma força extrafísica e não como uma forma racional.\n  PONTOS NEGATIVOS: Tendência à arrogância, ao nervosismo, à preguiça, ao egoísmo, à autopromoção, à traição e a menosprezar o semelhante.\n  ORIENTAÇÃO: Precisa aprender que justiça, cooperação e serviço prestado também fazem parte do cotidiano. Precisa aprender a penetrar nos problemas, até às suas últimas motivações de seus atos e as verdadeiras razões de seu proceder. Apesar de emocional e materialmente generoso, pode, às vezes, radicalizar, deixando-se levar por uma vida de luxo e glamour. Se cair no escapismo e se recusar a amadurecer, precisará aprender a ser responsável e a ter uma perspectiva mais madura. Porém, quando faz algo de que realmente gosta, é capaz de trabalhar arduamente e, com dedicação e perseverança, pode se realizar e ser bem-sucedido. Está destinado a ser Líder, pela sua capacidade executiva que se  estende por vasto campo, atingindo mesmo as fronteiras internacionais. No tocante à Magia, a mesma poderá ser construtiva ou destrutiva; o que semear, colherá!";
        }

        edtdestino.setText(""+ler+numero);

        intent.putExtra("VALORES1", valor1);
        intent.putExtra("VALORES2", valor2);
        intent.putExtra("VALORES3", valor3);
        intent.putExtra("VALORES4", valor4);
        intent.putExtra("VALORES5", valor5);
        intent.putExtra("VALORES6", valor6);
        intent.putExtra("VALORES7", valor7);
        intent.putExtra("VALORES8", valor8);
        intent.putExtra("VALORES9", valor9);
        intent.putExtra("VALORES10", valor10);
        intent.putExtra("VALORES11", valor11);
        intent.putExtra("VALORES12", valor12);
        intent.putExtra("VALORES13", valor13);
        intent.putExtra("VALORES14", valor14);
        intent.putExtra("VALORES15", valor15);
        intent.putExtra("VALORES16", valor16);
        intent.putExtra("VALORES17", valor17);
        intent.putExtra("VALORES18", valor18);
        intent.putExtra("VALORES19", valor19);
        intent.putExtra("VALORES20", valor20);
        intent.putExtra("VALORES21", valor21);
        intent.putExtra("VALORES22", valor22);
        intent.putExtra("VALORES23", valor23);
        intent.putExtra("VALORES24", valor24);
        intent.putExtra("VALORES25", valor25);
        intent.putExtra("VALORES26", valor26);
        intent.putExtra("VALORES27", valor27);
        intent.putExtra("VALORES28", valor28);


    }
}
